// Generated by https://quicktype.io

export interface TopLevel {
    Data: Datum[];
}

export interface Datum {
    userId:            number;
    jobTitleName:      string;
    firstName:         string;
    lastName:          string;
    preferredFullName: string;
    employeeCode:      string;
    region:            string;
    phoneNumber:       number;
    emailAddress:      string;
    employeeAge:       number;
    profileImage:      string;
}
